src/PhpSigep/Services/Real/FecharPreListaDePostagem.php
Retorna erro quando o objeto tem valor declarado.
=> Fechar PreLista

src/PhpSigep/Services/Real/FecharPreListaDePostagem.php
Quando preenchido o campo de diretoria não era retornado o numero dentro do getDiretoria.
=> Correção de um pequeno erro em fecharPreListaPostagem

.gitignore, src/PhpSigep/Pdf/CartaoDePostagem.php
Com essas modificações resolve-se o problema do sema.png, no qual não estava localizando este "arquivo" e gerando um erro ao imprimirEtiquetas.php.
=> Alterado a chamada da classe Semacode

src/PhpSigep/Pdf/CartaoDePostagem.php
O valor é expresso em kilogramas mas a legenda está em gramas.
=> Peso(g) -> Peso(kg) na impressão de etiqueta

src/PhpSigep/Pdf/CartaoDePostagem.php, src/PhpSigep/Pdf/Chancela/Carta.php, src/PhpSigep/Pdf/Chancela/Pac.php, src/PhpSigep/Pdf/Chancela/Sedex.php, src/PhpSigep/Pdf/ImprovedFPDF.php, src/PhpSigep/Services/SoapClient/Real.php
Geração das etiquetas seguindo padrão sugerido pelos correios; Utilizando medidas em milímetros e tamanho de folha padrão 100x140; Pequenas melhorias gerais;
=> Adequação ao modelo padrão sugerido pelos correios

src/PhpSigep/Pdf/CartaoDePostagem.php, src/PhpSigep/Pdf/Script/BarCode128.php
não sei exatamente pq você tinha deixado comentado a parte da PLP de aparecer na etiqueta.
Como ela só é mostrada se o parametro for >0 na chamada da classe, não vejo mal deixarmos ser possível alguém colocar essa info na etiqueta se quiser. Inclusive eu preciso :)
```php
public function __construct($plp, $idPlpCorreios, $logoFile)
```
Segue como fica a etiquta com PLP nesse PR:
=> colocando de volta PLP na etiqueta

src/PhpSigep/Pdf/CartaoDePostagem.php, src/PhpSigep/Pdf/ImprovedFPDF.php, src/PhpSigep/Pdf/ListaDePostagem.php
agora 'e possivel, por exemplo, mandar o PDF pro s3:
```php
require_once __DIR__ . '/sigep/bootstrap-exemplos.php';
$params = include __DIR__ . '/sigep/helper-criar-pre-lista.php';
$pdf  = new \PhpSigep\Pdf\ListaDePostagem($params);
$pdf_string = $pdf->render('S');			
$sdk = new Aws\S3\S3Client([
'version'     => 'latest',
'region'      => 'us-east-1',
'credentials' => [
'key'    => '[key]',
'secret' => '[secret]',
],
]);
$sdk->registerStreamWrapper();
file_put_contents("s3://[bucket]/[pdf_name].pdf", $pdf_string);
```
ah, no PR tem tb um small fix pra strict
=> criando a opcao do PDF virar BUFFER e com isso poder, por exemplo, fazer upload no s3

src/PhpSigep/Pdf/CartaoDePostagem.php
Ao tentar homologar a etiqueta junto aos Correios recebi a informação abaixo:
"R.: Os Correios brevemente implantarão um serviço de imagem.  Na nova etiqueta tem um campo para assinatura e colocação de documento.  Então, será fotografado e disponibilizado para o remetente a imagem da assinatura do objeto.
Falta apenas o campo da assinatura e do documento.  OK?"
Sendo assim, adicionei os campos pedidos na etiqueta.
=> Altera Layout Etiqueta

src/PhpSigep/Model/AccessData.php
Se o parâmetro $diretoria for inteiro tenta criar \PhpSigep\Model\Diretoria, senão verifica se é instancia de  \PhpSigep\Model\Diretoria
=> Inclusão de validação em setDiretoria na classe AccessData

exemplos/helper-criar-pre-lista.php, src/PhpSigep/Model/Dimensao.php, src/PhpSigep/Model/ServicoAdicional.php
Ajuste nas variáveis do Model/Dimensao e Model/ServicoAdicional para devolverem o valor com 3 dígitos e ajuste no helper-plp para adicionar o diametro() na dimensao e o valorDeclarado no ServicoAdicional
Essas alterações foram necessárias no meu caso para o Correios validarem o XML da PLP e as encomendas serem despachadas normalmente.
=> Ajuste nas variáveis do Model/Dimensao e Model/ServicoAdicional

src/PhpSigep/Pdf/CartaoDePostagem.php, src/PhpSigep/Pdf/CartaoDePostagem2016.php
Ajustes nas classes PhpSigep\Pdf\CartaoDePostagem2016 e PhpSigep\Pdf\CartaoDePostagem para gerar a chancela com o nome correto do serviços de Sedex (e-Sedex, Sedex 10, Sedex 12 e Sedex Hoje)
=> Ajuste no cartão de postagem para gerar chancela com nome correto dos Serviços

src/PhpSigep/Services/Real/SoapClientFactory.php
Corrigir variável onde é atribuído o retorno da chamada SOAP no método getSoapCalcPrecoPrazo() na classe SoapClientFactory
=> Corrigir variável onde é atribuído o retorno da chamada SOAP

src/PhpSigep/Model/ServicoDePostagem.php
Corrigido o erro `E_COMPILE_ERROR: Cannot redefine class constant PhpSigep\Model\ServicoDePostagem::SERVICE_SEDEX_CONTRATO_AGENCIA` da issue #132
=> Constantes repetidas removidas

src/PhpSigep/Model/ServicoDePostagem.php
Resolve a issue #136 onde o código do serviço (com zero a esquerda) retornado pelos Correios vem como um inteiro
=> Normaliza o código do serviço para o padrão de 5 caracteres

src/PhpSigep/Model/SolicitaEtiquetas.php
Alterar validação para `string`, uma vez que os códigos do serviço no Model passaram de `int` para `string`
=> Alterar validação do código de serviço dos correios

README.md, src/PhpSigep/Model/SolicitaXmlPlpResult.php, src/PhpSigep/Pdf/CartaoDePostagem2016.php, src/PhpSigep/Services/Real/Exception/SolicitaXmlPlp/FailedConvertToArrayException.php, src/PhpSigep/Services/Real/Exception/SolicitaXmlPlp/FailedConvertXmlException.php, src/PhpSigep/Services/Real/Exception/SolicitaXmlPlp/FailedResultException.php, src/PhpSigep/Services/Real/SolicitaXmlPlp.php, src/PhpSigep/Services/SoapClient/Real.php
retornando Xml da PLP após a mesmo ter sido processada pelo Sara, isso é útil para o lojista salvar as informações da PLP para diversos tipos de possibilidades posteriores.
=> Implementado método para retornar o XML da plp após processamento

src/PhpSigep/Model/ServicoDePostagem.php, src/PhpSigep/Pdf/CartaoDePostagem.php
Recebi um comunicado da ECT sobre os novos códigos para os clientes com contrato.
A ECT informa que a partir de 06/05/2017, os códigos a faturar até então vigentes deixaram de funcionar, ficando mantidos os novos códigos disponíveis abaixo:
· 04162 - SEDEX CONTRATO; - **NÃO MUDOU**
· 04170 - SEDEX REVERSO ESPELHO 04162; - **NOVO**
· 04189 - SEDEX PAGAMENTO ENTREGA; - **MUDOU**
· 04669 - PAC AGENCIA; -  **NÃO MUDOU**
· 04677 - PAC REVERSO ESPELHO 04669;  - **NOVO**
· 04685 - PAC PAGAMENTO ENTREGA; - **NOVO**
· 04693 - PAC GRANDES FORMATOS; - **MUDOU**
Os códigos do _PAC REVERSO ESPELHO_ e _SEDEX REVERSO ESPELHO_ eu já tinha colocado em uma PR anterior no entanto o @andersonls me avisou sobre o formato inválido do código, o mesmo deve ser sem o hífen.
=> Novos códigos para a prestação dos serviços de Encomendas

src/PhpSigep/Services/Real/SoapClientFactory.php
Estava apitando o warning abaixo e parou após comentário.
`PHP Warning: Uncaught ErrorException: SoapClient::SoapClient(): Failed to enable crypto in /var/www/html/.../vendor/stavarengo/php-sigep/src/PhpSigep/Services/Real/SoapClientFactory.php:115`
=> Comentando o cipher no rastreio de objetos

src/PhpSigep/Services/Real/SolicitaXmlPlp.php
Adicionando LIBXML_NOCDATA na função simplexml_load_string para converter os valores com CDATA corretamente.
=> Adicionando LIBXML_NOCDATA

src/PhpSigep/Services/Real/SolicitaXmlPlp.php
Com a remoção do CDATA caracteres especiais são convertidos de forma incorreta
@stavarengo 
Percebi depois que os campos com CDATA que possam conter caracteres especiais podem ser apresentados de forma incorreta.
Fiz a troca da codificação para não ocorrer essa situação.
=> Acertando encodificação

src/PhpSigep/Services/Real/SolicitaXmlPlp.php
Processamos cerca de 20000 itens e 0,1% apresentaram alguns caracteres que o iconv não consegue converter, nesse caso adicionei o ignore para que não sejá gerada uma exceção.
=> Adicionado ignore ao iconv

src/PhpSigep/Pdf/CartaoDePostagem.php, src/PhpSigep/Pdf/CartaoDePostagem2016.php
Isso da compatibilidade com impressoras argox, tendo as mesmas configurações da etiqueta do mercado livre
=> Alinhando nome e documento com destinatário no pdf de cartão de postagem

src/PhpSigep/Model/ServicoDePostagem.php
Adicionado o tipo Sedex 10 ao PhpSigep\Model\ServicoDePostagem;
Junto do seu codigo de Serviço.
Atualmente se for realizado uma Chamada do ServicoDePostagem(ServicoDePostagem::SERVICE_SEDEX_10) vai resultar em uma Exception pois falta a declaração do serviço no array $services
=> Adicionar Sedex_10 ao ServicoDePostagem Model

composer.json, src/PhpSigep/Services/Real/FecharPreListaDePostagem.php
O mb_substr, por ser multi-byte safe, lida corretamente com UTF-8 e evita erros de codificação no XML da PLP.
Exemplos:
```php
<?php
$str = 'éééé';
var_dump(strlen($str)); // int(8)
var_dump(mb_strlen($str)); // int(4)
$sub = substr($str, 0, 3);
var_dump($sub); // string(3) "é"
var_dump(strlen($sub)); // int(3)
var_dump(mb_strlen($sub)); // int(2)
$mb_sub = mb_substr($str, 0, 3);
var_dump($mb_sub); // string(6) "ééé"
var_dump(strlen($mb_sub)); // int(6)
var_dump(mb_strlen($mb_sub)); // int(3)
```
Repare que no `string(3) "é"`  apesar de mostrar um caractere tem um byte sobrando que causa o erro de codificação.
=> Substitui utilização do substr pelo mb_substr (multi-byte safe)

src/PhpSigep/Pdf/ListaDePostagem.php
O peso na etiqueta era exibido em gramas e aqui em kg, padronizado para mostrar em gramas.
=> Mostrar peso em gramas

composer.json
Alteração feita para poder subir as novas tags no Packagist, conforme sugerido em
https://github.com/composer/packagist/issues/649
Deve fechar a issue https://github.com/stavarengo/php-sigep/issues/306.
=> Remover versão fixa do composer.json

src/PhpSigep/Config.php, src/PhpSigep/Services/Real/FecharPreListaDePostagem.php
Tentado solucionar o problema da dúvida #298 , fiz alterações para que por meio de configuração o usuário possa escolher o encode do XML que é enviado aos correios, conforme interesse, entre UTF-8 ou ISO-8859-1, como abaixo:
```
// Escolhe ISO-8859-1
$config->setXmlEncode(\PhpSigep\Config::XML_ENCODE_ISO);
```
ou
```
// Escolhe UTF-8
$config->setXmlEncode(\PhpSigep\Config::XML_ENCODE_UTF);
```
Precisando de alguma melhoria, aguardo comentários.
@andersonls  e @stavarengo Obrigado.
=> Melhoria Encode

src/PhpSigep/Pdf/ListaDePostagem.php, src/PhpSigep/Services/Real/FecharPreListaDePostagem.php
Motivo: Os correios agora trabalha com 3 códigos de serviços que não depende do número de contrato utilizado para aquela etiqueta (019,024 e 064).
Exemplo, Ao gerar uma etiqueta para o contrato de numero 04669 (PAC), pode-se utilizar o número do código de serviço adicional 064 - National Standard. Porem este mesmo código de serviço (064) pode ser enviado quando o numero de contrato for 04332 (pac abcomm) ou 04677 (pac reverso) entre outros números.
Com esta alteração, valida-se apenas o campo positivo, ou seja, maior que 0 para o parametro "ValorDeclarado"
=> Envio do parametro de ValorDeclarado, independente do código do serviço adicional.

src/PhpSigep/Pdf/CartaoDePostagem2018.php
Reduzido o tamanho da fonte da etiqueta para que possa mostrar o destinatário e remetente com nomes grandes.
Removido a conversão para inteiro na etiqueta que estava quebrando quando a nota fiscal começa com zero a esquerda.
=> Alteração na etiqueta - CartaoDePostagem2018

src/PhpSigep/Services/Real/FecharPreListaDePostagem.php
Para homologação da PLP e validação do seu XML com o XSD disponibilizado pelos Correios, foi necessário inserir todas as tags de XML, conforme documentação do SIGEPWEB.
=> Ajustes para tags de xml obrigatórias da PLP

src/PhpSigep/Pdf/CartaoDePostagem2018.php
Após o PR #408, foi visto que ficaram muitos zeros a esquerda, onde estava sobrepondo outras informações, após alguns testes, vendo que se deixar o preenchimento máximo de 10 caracteres fica normalizado
=> Remoção de zeros a esquerda

src/PhpSigep/Pdf/Script/CircularText.php
Está dando erro  Parse error: syntax error, unexpected ';', expecting ')' in \vendor\stavarengo\php-sigep\src\PhpSigep\Pdf\Script\CircularText.php on line 18
na versão php 7.2.4 e possivelmente deve dar o mesmo erro outras versões
=> Correção de bug na classe CircularText o for estava com 4 parametros

src/PhpSigep/Pdf/CartaoDePostagem2018.php
- CAKE PHP 2.x com DEBUG[2] - Sem ocorrências
- Validação em outras etiquetas que não apresentaram problema
=> Caractere illegal, não imprime informações na etiqueta

src/PhpSigep/Cache/InvalidAdapterException.php
Ao rodar o composer está mostrando esse warning, mas esta classe não está sendo usada em nenhum lugar.
`Deprecation Notice: Class PhpSigep\Cache\Storage\Adapter\Exception\InvalidAdapterException located in ./vendor/stavarengo/php-sigep/src/PhpSigep/Cache/InvalidAdapterException.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201`
=> Removendo classe não utilizada - Suporte Composer v2.0 

src/PhpSigep/Model/ServicoDePostagem.php, src/PhpSigep/Pdf/CartaoDePostagem2018.php
Adicionado código de serviço para "Carta Registrada" com contrato BRONZE nos correios.
Testado e funcionando com a impressão pelo modelo de etiqueta 2018.
Se alguém precisar adicionar de algum outro contrato (ex.: Ouro 2, Prata 1, etc) só fazer o mesmo que eu fiz com base na imagem. PS lembrar de obter o idServico correto, no buscaCliente aparece, aí basta criar uma nova entrada e colocar no lugar do 162142 e valores do 99999 aqui `self::SERVICE_CARTA_REGISTRADA_AGENCIA_99999 => ['Carta Registrada 99999', 162142],` além de adicionar no switch case do CartaoDePostagem2018
=> Adicionado código de carta regristrada contrato bronze

.github/workflows/ci.yml, .gitignore, composer.json, composer.lock, phpstan-baseline.neon, phpstan.neon, src/PhpSigep/Services/SoapClient/Simulador.php
Adicionei a análise estática no nível mais básico para detectar erros de sintaxe mais simples. Também incluí o composer.lock no rastreamento do repositório pois é o recomendado para garantir que no cliente seja executada a mesma versão. 
Também implementei alguns método na classe Simulador.
Como podem ver pelo arquivo baseline tem erros sendo ignorados. Posso corrigir eles quando tiver um tempo.
RFC: O que acham de colocarmos a versão mínima do php para 7.3 que é a última atualmente que recebe atualizações de segurança?
=> PHPStan + Github Actions e algumas correções

src/PhpSigep/Pdf/ListaDePostagem.php
Adiciona um terceiro parâmetro não obrigatório no construtor de PhpSigep\Pdf\ListaDePostagem que se vier preenchido, é exibido entre o ID da PLP e o nome do cliente
Antes, sem a data:
Depois, com a data:
=> Adiciona a data de geração da PLP no PDF

src/PhpSigep/Pdf/CartaoDePostagem.php, src/PhpSigep/Pdf/CartaoDePostagem2016.php, src/PhpSigep/Pdf/CartaoDePostagem2018.php
Na documentação dos correios, é solicitado que quando a soma dos dígitos do CEP forem igual a um múltiplo de 10, o digito verificador deve ser igual a 0.
=> :bug: alterando lógica de CalcDigCep para retornar 0 ao inves de 10

src/PhpSigep/Model/ServicoAdicional.php, src/PhpSigep/Model/ServicoDePostagem.php, src/PhpSigep/Pdf/CartaoDePostagem2018.php, src/PhpSigep/Services/Real/CalcPrecoPrazo.php, src/PhpSigep/Services/SoapClient/Simulador.php
- Adicionado cód. serviços para mini envios (04227, 04235, 04391).
- Adicionado serviço adicional de valor declarado para mini envios e carta.
- Adicionado mini envios na impressão de etiquetas CartaoDePostagem2018
* *Não foi adicionado chancelas para imprimir com CartaoDePostagem e CartaoDePostagem2016.
=> Mini Envios

src/PhpSigep/Model/Destinatario.php, src/PhpSigep/Services/Real/FecharPreListaDePostagem.php
* Adicionado o campo identificacao ao destinatario
* Adicionado valor a tag cpf_cnpj_destinatario do destinatario e do remetente no fechamento da PLP
Motivo da alteração: Recebemos um comunicado dos Correios dizendo que a partir de 01/01/2022 o campo cpf/cnpj do destinatário será obrigatório para encomendas que acompanham nota fiscal. Esta alteração deve prover os campos necessários para cumprir com esta exigeência dos Correios.
=> Demanda Correios - CPF/CNPJ obrigatórios para remessas com NF

src/PhpSigep/Model/Remetente.php, src/PhpSigep/Services/Real/FecharPreListaDePostagem.php
* Adicionando o campo número de celular ao Remetente
* Preenchendo a tag celular_remetente com o campo celular adicionado a classe Remetente
* Formatando o celular para evitar problemas com o fechamento do PLP
* corrigindo o tamanho máximo da tag celular_remetente para 12
Motivo da alteração: A tag celular_remetente estava sendo preenchida com o campo telefone e o campo não estava sendo formatado / sanitizado, ou seja, se o campo telefone contivesse um valor com parenteses ou espaços, o fechamento da PLP ocorria, mas a etiqueta estava sendo rejeitada pelo sistema dos correios após a postagem.
=> Adicionando e formatando o campo número de celular ao Remetente e a PLP

exemplos/solicitarPostagemReversa.php, src/PhpSigep/Model/Destinatario.php, src/PhpSigep/Model/Remetente.php, src/PhpSigep/Services/Real/FecharPreListaDePostagem.php, src/PhpSigep/Services/Real/PreListaDePostagem/GerarXmlPreListaDePostagem.php, tests/BootstrapTrait.php, tests/Builders/PreListaDePostagemBuilder.php, tests/Fakes/SoapClientFake.php, tests/PhpSigep/Services/Real/FecharPreListaDePostagemTest.php, tests/PhpSigep/Services/Real/PreListaDePostagem/GerarXmlPreListaDePostagemTest.php, tests/Xml/Util.php, tests/resources/xml/modelo_plp1-utf8.xml
No geral são melhorias para com php 8.1, onde tive os warnings na imagem abaixo. Porém como não haviam testes automatizados para garantir que minha alteração funciona, tive que mexer em mais arquivos... Se o PR estiver muito grande posso tentar quebrar em mais.
- Removi campo referencia e sms, pois não vi uso para elas. Não são incluídas no xml
- em `PhpSigep\Model\Destinatario` e `PhpSigep\Model\Remetente` corrigi o php doc dos atributos, os opcionais aceitam null
- extraí uma classe de `src/PhpSigep/Services/Real/FecharPreListaDePostagem.php`, isolei a parte que monta o xml para facilitar os testes automatizados e diminuir responsabilidades da classe. A classe responsável por gerar o xml é a `src/PhpSigep/Services/Real/PreListaDePostagem/GerarXmlPreListaDePostagem.php`
- Criei um teste …
=> Melhorias para PHP 8.1 e mais testes automatizados

src/PhpSigep/Model/RastrearObjetoEvento.php, src/PhpSigep/Services/Real/RastrearObjeto.php, src/PhpSigep/Services/Real/RastrearObjetoLista.php, src/PhpSigep/Services/SoapClient/Real.php
O campo de destino não é tão mais útil no rastreamento, mas mostra a cidade para qual o pacote está indo, e pode ser a cidade errada.
O campo de endereço é útil para identificar onde o pacote deve ser retirado pelo destinatário, ou em caso de retorno, pelo remetente.
A classe RastrearObjetoLista permite o rastreamento de até 50 objetos por vez, agilizando o rastreamento de um volume grande de envios. Aconselho obter somente o último movimento.
Estou com problema no meu firewall e não consegui fazer o pull diretamente do netbeans, tive que alterar os arquivos manualmente. Pode ser que está faltando alguma coisa.
=> Adição dos campos de "destino" e "endereco" em rastrear Objeto e adição da classe RastrearObjetoLista

.github/workflows/ci.yml, src/PhpSigep/Pdf/ImprovedFPDF.php
A ideia é corrigir o seguinte warning ao executar com PHP 8.2:
`deprecated: 8192 :: Creation of dynamic property PhpSigep\Pdf\VariableStream::$context is deprecated on line 1232 of .../vendor/stavarengo/php-sigep-fpdf/fpdf.php`
=> Adding property context
