stavarengo/php-sigep

src/PhpSigep/Pdf/CartaoDePostagem.php, src/PhpSigep/Pdf/Semacode.php, src/PhpSigep/Pdf/sema.php
Usada a Classe Semacode() - https://github.com/splitbrain/
=> Adicionada a Matrix 2D ao Cartão de Postagem

src/PhpSigep/Pdf/CartaoDePostagem.php, src/PhpSigep/Pdf/ImprovedFPDF.php
- Adjusting some element positions;
- Added 2D Data Matrix as image stream (avoiding file system permissions error)
=> Fixings & Improvements

src/PhpSigep/Services/SoapClient/Real.php
Erro de digitação que peguei ao depurar o serviço
=> rádido -> rápido nos comentários

src/PhpSigep/Pdf/ImprovedFPDF.php
Added feature to append javascript into PDF; Added 'auto print' feature enabling pdf start to print automatically after opening
=> Javascript features

src/PhpSigep/Services/Real/SoapClientFactory.php
solution by @vitalibr
http://stackoverflow.com/questions/34609448/soap-error-parsing-wsdl-couldnt-load-from-xampp
=> fix for OpenSSL > 1.0

src/PhpSigep/Model/ServicoDePostagem.php
falta esse serviço no model **ServicoDePostagem.php**
=> Adicionando servicoDePostagem Carta Comercial Registrada CTR EP MÁQ FRAN

src/PhpSigep/Model/VerificarStatusCartaoPostagemResposta.php, src/PhpSigep/Services/Real/VerificarStatusCartaoPostagem.php, src/PhpSigep/Services/ServiceInterface.php, src/PhpSigep/Services/SoapClient/Real.php
Criar método para consultar o status do cartão postagem
=> Método para verificar o status do cartão postagem

src/PhpSigep/Services/Real/CalcPrecoPrazo.php, src/PhpSigep/Services/Real/FecharPreListaDePostagem.php, src/PhpSigep/Services/Real/SolicitaEtiquetas.php
Baseado na resposta: http://stackoverflow.com/a/7508191
=> Bugfix: issue #65

src/PhpSigep/Services/Real/RastrearObjeto.php
lecionada, antes só listava o último
=> Lista todos os eventos no rastreio do objeto caso essa opção seja se

src/PhpSigep/Services/Real/CalcPrecoPrazo.php
=> Verifica a propriedade CalcPrecoPrazoResult com a função property_exists

src/PhpSigep/Model/SolicitaEtiquetas.php
Atualiza a mensagem da exception para se adequar a #141
=> Atualiza a mensagem da exception

src/PhpSigep/Model/ServicoDePostagem.php
Adiciona:
SERVICE_SEDEX_REVERSO_CONTRATO_AGENCIA
SERVICE_PAC_REVERSO_CONTRATO_AGENCIA
=> Adiciona novos códigos de serviço

src/PhpSigep/Model/ServicoDePostagem.php, src/PhpSigep/Pdf/CartaoDePostagem.php
=> Atualiza códigos de serviço do SEDEX e PAC sem contrato

src/PhpSigep/Pdf/ImprovedFPDF.php, src/PhpSigep/Services/Real/SolicitaEtiquetas.php, tests/Services/DigitoVerificadorTest.php, tests/Services/SolicitaEtiquetasTest.php
Antes tinha enviado da conta errada,
O certo é esse pull request
=> Correção nos números sequenciais de etiquetas 

src/PhpSigep/Pdf/CartaoDePostagem.php
Para mais de uma etiqueta.
Volume: 1/3
Volume: 2/3
Volume: 3/3
=> Ajuste na impressão (pdf) do Volume sequencial

exemplos/solicitarEtiquetas.php
Foi ajustado o title do exemplo de solicitação de etiquetas.
=> Ajustes no Title do exemplo

src/PhpSigep/Model/ServicoDePostagem.php
=> Cadastro dos novos códigos referentes a liminar da ABCOMM

exemplos/helper-criar-pre-lista-a4.php, src/PhpSigep/Model/ObjetoPostal.php, src/PhpSigep/Pdf/CartaoDePostagem2016.php
Fiz essas alterações para um projeto interno, mas caso se enquadre no escopo do projeto fica ai o PR!
=> Campos de pedido e observação na etiqueta 2016 (#1)

src/PhpSigep/Pdf/CartaoDePostagem2018.php
Correção no arquivo CartaoDePostagem2018.php onde as constantes estavam diferentes do ServicoDePostagem.
=> Correção de constantes de acordo com o arquivo de ServicoDePostagem;

src/PhpSigep/Services/Real/SoapClientFactory.php
Melhorias para que a primeira conexão ganhe mais velocidade.
Issues #280
=> Melhoria na velocidade de conexão

exemplos/solicitarPostagemReversa.php, src/PhpSigep/Config.php, src/PhpSigep/Model/AccessData.php, src/PhpSigep/Model/AccessDataHomologacaoReversa.php, src/PhpSigep/Model/ColetasSolicitadas.php, src/PhpSigep/Model/Destinatario.php, src/PhpSigep/Model/ObjCol.php, src/PhpSigep/Model/Remetente.php, src/PhpSigep/Model/SolicitarPostagemReversa.php, src/PhpSigep/Model/SolicitarPostagemReversaRetorno.php, src/PhpSigep/Services/Real/SoapClientFactory.php, src/PhpSigep/Services/Real/SolicitarPostagemReversa.php, src/PhpSigep/Services/SoapClient/Real.php
Implantação da Reversa no projeto PHP-SIGEP
=> Implantado reversa

src/PhpSigep/Model/CancelarObjetoResposta.php, src/PhpSigep/Services/Real/CancelarObjeto.php, src/PhpSigep/Services/ServiceInterface.php, src/PhpSigep/Services/SoapClient/Real.php
Criado o método que permite fazer o cancelamento de um objeto PLP.
=> Adicionado função para fazer o cancelamento de um objeto PLP

src/PhpSigep/Services/Real/ConsultaCep.php
No arquivo src/PhpSigep/Services/Real/ConsultaCep.php alguém esqueceu de fechar as {} de um if, esse pull request corrige isso.
=> Correção de bug na validação de dados da consulta de cep

src/PhpSigep/Pdf/Script/CircularText.php
Olá, obrigado pelo excelente projeto!
Esse é meu primeiro PR neste projeto, apenas uma pequena atualização de código :)
Creio que ninguém mais usa PHP 4, e o 7 já tornou obsoleto essa forma de declarar o construtor, então acredito que já é possível atualizar, certo? A outra mudança é só uma pequena otimização.
=> Construtor obsoleto, Retirada de função em loop

src/PhpSigep/Services/SoapClient/Real.php
Remoção de atribuições mortas em listarAgenciasCliqueRetireByCep()
Atualização de cabeçalhos phpdoc
=> Atribuições não usadas/Atualização phpdoc

src/PhpSigep/Services/Real/CalcPrecoPrazo.php
A variável $r pode não ter sido definida após try - catch
=> Variável $r pode não ter sido definida

src/PhpSigep/Config.php, src/PhpSigep/Services/Real/CadastrarPI.php, src/PhpSigep/Services/Real/SoapClientFactory.php, src/PhpSigep/Services/ServiceInterface.php, src/PhpSigep/Services/SoapClient/Real.php
O Fale Conosco do Correios tem diversos nomes, mas usei o nome do recurso PedidoInformacao para criar a classe.
O passo de consultar tem um erro na documentação, falta uma variável. Aliás nem está na documentação enviada para mim, encontrei no site.
=> Adiciona Cadastramento de PI - Fale Conosco

exemplos/helper-criar-pre-lista.php, exemplos/imprimirEtiquetasA4.php, exemplos/solicitarEtiquetas.php, phpstan-baseline.neon, src/PhpSigep/Pdf/Semacode.php, tests/Services/SolicitaEtiquetasTest.php
Remoção de algumas constantes não utilizadas e nome de variável errada.
=> Correções diversas

src/PhpSigep/Pdf/CartaoDePostagem.php
Adiciona campo complemento na matrix2d.
=> Adiciona complemento na matrix2d

src/PhpSigep/Pdf/CartaoDePostagem.php
Adicionado os novos serviços de postagem para impressão correta da chancela.
=> Adiciona novos serviços no cartão de postagem

src/PhpSigep/Model/ServicoDePostagem.php
Retorna um array com os Serviços de postagem incluídos no array de entrada
=> Adiciona getFromArray($arrayServicesCode)

exemplos/consultaColeta.php, src/PhpSigep/Model/ConsultarColeta.php, src/PhpSigep/Model/ConsultarColetaRetorno.php, src/PhpSigep/Services/Real/ConsultarColeta.php, src/PhpSigep/Services/SoapClient/Real.php
Olá Pessoal,
Estou usando php sigep para implementar os serviços dos correios aqui onde trabalho.
Está sendo de grande utilidade.
Vou colaborar com tudo que for preciso.
Adicionado consulta de coletas solicitadas pelo serviço de logistica reversa.
=> Consulta de Coletas Solicitadas Pelo Serviço de Logistica Reversa

src/PhpSigep/Services/Real/FecharPreListaDePostagem.php
PR referente a issue https://github.com/stavarengo/php-sigep/issues/477
=> Fix gerando valor declarado a mais

src/PhpSigep/Model/ServicoDePostagem.php, src/PhpSigep/Pdf/CartaoDePostagem2018.php
Ref: https://github.com/stavarengo/php-sigep/pull/451
=>  Adicionado código de carta regristrada contrato ouro 4

src/PhpSigep/Pdf/CartaoDePostagem.php
Este PR adiciona o contrato 03220 de Sedex no CartaoDePostagem.php para que possa reconhecer e adicionar a chancela do SEDEX
=> Add contrato SEDEX 03220 no CartaoDePostagem.php

src/PhpSigep/Config.php, src/PhpSigep/Model/LogisticaReversa.php, src/PhpSigep/Model/LogisticaReversaColeta.php, src/PhpSigep/Model/LogisticaReversaDestinatario.php, src/PhpSigep/Model/LogisticaReversaObjeto.php, src/PhpSigep/Model/LogisticaReversaPedido.php, src/PhpSigep/Model/LogisticaReversaPedidoResposta.php, src/PhpSigep/Model/LogisticaReversaProduto.php, src/PhpSigep/Model/LogisticaReversaRemetente.php, src/PhpSigep/Services/Real/LogisticaReversaAcompanharPedidoData.php, src/PhpSigep/Services/Real/LogisticaReversaAcompanharPedidoNumero.php, src/PhpSigep/Services/Real/LogisticaReversaCancelarPedido.php, src/PhpSigep/Services/Real/LogisticaReversaCriarPedido.php, src/PhpSigep/Services/Real/SoapClientFactory.php, src/PhpSigep/Services/SoapClient/Real.php
Logística Reversa com Criação, Cancelamento, Pesquisa por Número e Data
=> Adição de Logística Reversa
